// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXnauXoVjkMPADb_VO6XOMQYpKD_V56G4',
    appId: '1:872870500181:web:20d01af0ff22a1bb5481dc',
    messagingSenderId: '872870500181',
    projectId: 'classcentral-2c99c',
    authDomain: 'classcentral-2c99c.firebaseapp.com',
    storageBucket: 'classcentral-2c99c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7ShyArkOyLoN4yarfIt3kObuKjbhf4A',
    appId: '1:872870500181:android:f94945ff44c7e2f05481dc',
    messagingSenderId: '872870500181',
    projectId: 'classcentral-2c99c',
    storageBucket: 'classcentral-2c99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6JmJEQeaNPzScnmhmrNm1ZqbwTmwRFg',
    appId: '1:872870500181:ios:e9c6c809d13037ae5481dc',
    messagingSenderId: '872870500181',
    projectId: 'classcentral-2c99c',
    storageBucket: 'classcentral-2c99c.firebasestorage.app',
    iosBundleId: 'com.example.classcentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG6JmJEQeaNPzScnmhmrNm1ZqbwTmwRFg',
    appId: '1:872870500181:ios:e9c6c809d13037ae5481dc',
    messagingSenderId: '872870500181',
    projectId: 'classcentral-2c99c',
    storageBucket: 'classcentral-2c99c.firebasestorage.app',
    iosBundleId: 'com.example.classcentral',
  );
}
